version: "3"

services:

  base:
    build:
      dockerfile: Dockerfile.${BASE_DOCKER_VERSION}
      context: base/$OSNAME
    # TODO ${VAR:-} raises error in docker-compose < 1.21.0
    image: sovrin/base:${BASE_DOCKER_VERSION}-${OSNAME}

  rust:
    build:
      dockerfile: Dockerfile.${RUST_DOCKER_VERSION}
      context: rust/$OSNAME
      args:
          - RUST_VERSION
    image: sovrin/rust:${RUST_DOCKER_VERSION}-${OSNAME}

  python3:
    build:
      dockerfile: Dockerfile.${PYTHON3_DOCKER_VERSION}
      context: python3/$OSNAME
      args:
          - PYTHON3_VERSION
    image: sovrin/python3:${PYTHON3_DOCKER_VERSION}-${OSNAME}
